/**
 * TAMVArtifact & KnowledgeCell Domain Types
 * Central data model for knowledge cells and published artifacts
 */

export type CellType =
  | 'Render3D'
  | 'Render4D'
  | 'IA-ImmersiveFX'
  | 'QuantumChannel'
  | 'SensorMultiFX'
  | 'APIIntegration'
  | 'Analytics'
  | 'UIControl'
  | 'SpatialLogic';

export type ArtifactType = 'CODE' | 'DATASET' | 'PAPER' | 'SPEC' | 'MIXED';
export type ArtifactStatus = 'DRAFT' | 'PUBLISHED' | 'ARCHIVED';

/**
 * Knowledge Cell: Microservice/capability unit in TAMV ecosystem
 */
export interface KnowledgeCell {
  id: string;
  type: CellType;
  description: string;
  version: string;
  dependencies?: string[]; // other cell.id required
  inputFormat: string; // 'OBJ', 'JSON', 'BLOB', 'WebRTC'
  outputFormat: string; // 'GLTF', 'JSON', 'WebXR', '4DState'
  iaSpecializationPrompt: string; // AI specialization directive
  apiEndpoint: string; // REST endpoint
  microserviceUrl: string; // containerized service URL
  testCases: string[]; // test scenario descriptions
  visualizationSample: string; // link or hash to visual demo
  author: string;
  created: Date;
  updated: Date;
}

/**
 * TAMVArtifact: Unified artifact model across GitHub/Zenodo/Figshare
 */
export interface TAMVArtifact {
  id: string; // UUID v4 generated by Kernel
  type: ArtifactType;
  metadata: {
    title: string;
    description: string;
    authors: {
      tamvUserId: string;
      orcid?: string;
      name?: string;
      email?: string;
    }[];
    keywords?: string[];
    tags?: string[];
  };
  targets: {
    github_hash?: string; // commit/tree hash reference
    zenodo_doi?: string;
    zenodo_deposit_id?: number;
    figshare_id?: number;
    figshare_doi?: string;
  };
  status: ArtifactStatus;
  createdAt: string; // ISO 8601
  updatedAt: string;
  createdBy: string; // tamvUserId
}

/**
 * KnowledgeRepo: Graph of cells and their relations
 */
export interface KnowledgeRepo {
  cells: Record<string, KnowledgeCell>;
  relations: Array<{
    from: string;
    to: string;
    relation: 'requires' | 'extends' | 'composes';
  }>;
  aiExpertiseProfile: string; // Base prompt for AI specialization
}

/**
 * Artifact with metadata for persistence
 */
export interface PersistedArtifact extends TAMVArtifact {
  _v: number; // Version for optimistic locking
  _hash?: string; // Content hash for integrity
}
