/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as RdmRouteImport } from './routes/rdm'
import { Route as Mdx5RouteImport } from './routes/mdx5'
import { Route as KorimaRouteImport } from './routes/korima'
import { Route as KernelRouteImport } from './routes/kernel'
import { Route as EoctRouteImport } from './routes/eoct'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as BookpiRouteImport } from './routes/bookpi'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FederationsIdRouteImport } from './routes/federations.$id'
import { Route as ApiRdmManifestRouteImport } from './routes/api/rdm/manifest'
import { Route as ApiPublicSystemicRouteImport } from './routes/api/public/systemic'
import { Route as ApiPublicStoresRouteImport } from './routes/api/public/stores'
import { Route as ApiPublicQueryRouteImport } from './routes/api/public/query'
import { Route as ApiPublicManifestRouteImport } from './routes/api/public/manifest'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiGithubEventsRouteImport } from './routes/api/github/events'
import { Route as ApiRdmWebhooksStripeRouteImport } from './routes/api/rdm/webhooks/stripe'
import { Route as ApiRdmPaymentsCreateRouteImport } from './routes/api/rdm/payments/create'
import { Route as ApiRdmEconomyRewardRouteImport } from './routes/api/rdm/economy/reward'
import { Route as ApiRdmCommerceCreateRouteImport } from './routes/api/rdm/commerce/create'
import { Route as ApiRdmAuthRegisterRouteImport } from './routes/api/rdm/auth/register'
import { Route as ApiRdmAiAskRouteImport } from './routes/api/rdm/ai/ask'
import { Route as ApiPublicManifestHistoryRouteImport } from './routes/api/public/manifest/history'
import { Route as ApiPublicManifestCompareRouteImport } from './routes/api/public/manifest/compare'
import { Route as ApiPublicAuditTraceIdRouteImport } from './routes/api/public/audit.$traceId'
import { Route as ApiKernelArtifactsSyncRouteImport } from './routes/api/kernel/artifacts/sync'
import { Route as ApiKernelArtifactsAuditRouteImport } from './routes/api/kernel/artifacts/audit'
import { Route as ApiGithubEventsStreamRouteImport } from './routes/api/github/events/stream'

const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const RdmRoute = RdmRouteImport.update({
  id: '/rdm',
  path: '/rdm',
  getParentRoute: () => rootRouteImport,
} as any)
const Mdx5Route = Mdx5RouteImport.update({
  id: '/mdx5',
  path: '/mdx5',
  getParentRoute: () => rootRouteImport,
} as any)
const KorimaRoute = KorimaRouteImport.update({
  id: '/korima',
  path: '/korima',
  getParentRoute: () => rootRouteImport,
} as any)
const KernelRoute = KernelRouteImport.update({
  id: '/kernel',
  path: '/kernel',
  getParentRoute: () => rootRouteImport,
} as any)
const EoctRoute = EoctRouteImport.update({
  id: '/eoct',
  path: '/eoct',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const BookpiRoute = BookpiRouteImport.update({
  id: '/bookpi',
  path: '/bookpi',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FederationsIdRoute = FederationsIdRouteImport.update({
  id: '/federations/$id',
  path: '/federations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRdmManifestRoute = ApiRdmManifestRouteImport.update({
  id: '/api/rdm/manifest',
  path: '/api/rdm/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSystemicRoute = ApiPublicSystemicRouteImport.update({
  id: '/api/public/systemic',
  path: '/api/public/systemic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStoresRoute = ApiPublicStoresRouteImport.update({
  id: '/api/public/stores',
  path: '/api/public/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQueryRoute = ApiPublicQueryRouteImport.update({
  id: '/api/public/query',
  path: '/api/public/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestRoute = ApiPublicManifestRouteImport.update({
  id: '/api/public/manifest',
  path: '/api/public/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubEventsRoute = ApiGithubEventsRouteImport.update({
  id: '/api/github/events',
  path: '/api/github/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRdmWebhooksStripeRoute = ApiRdmWebhooksStripeRouteImport.update({
  id: '/api/rdm/webhooks/stripe',
  path: '/api/rdm/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRdmPaymentsCreateRoute = ApiRdmPaymentsCreateRouteImport.update({
  id: '/api/rdm/payments/create',
  path: '/api/rdm/payments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRdmEconomyRewardRoute = ApiRdmEconomyRewardRouteImport.update({
  id: '/api/rdm/economy/reward',
  path: '/api/rdm/economy/reward',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRdmCommerceCreateRoute = ApiRdmCommerceCreateRouteImport.update({
  id: '/api/rdm/commerce/create',
  path: '/api/rdm/commerce/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRdmAuthRegisterRoute = ApiRdmAuthRegisterRouteImport.update({
  id: '/api/rdm/auth/register',
  path: '/api/rdm/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRdmAiAskRoute = ApiRdmAiAskRouteImport.update({
  id: '/api/rdm/ai/ask',
  path: '/api/rdm/ai/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestHistoryRoute =
  ApiPublicManifestHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ApiPublicManifestRoute,
  } as any)
const ApiPublicManifestCompareRoute =
  ApiPublicManifestCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => ApiPublicManifestRoute,
  } as any)
const ApiPublicAuditTraceIdRoute = ApiPublicAuditTraceIdRouteImport.update({
  id: '/api/public/audit/$traceId',
  path: '/api/public/audit/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKernelArtifactsSyncRoute = ApiKernelArtifactsSyncRouteImport.update({
  id: '/api/kernel/artifacts/sync',
  path: '/api/kernel/artifacts/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKernelArtifactsAuditRoute = ApiKernelArtifactsAuditRouteImport.update({
  id: '/api/kernel/artifacts/audit',
  path: '/api/kernel/artifacts/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubEventsStreamRoute = ApiGithubEventsStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiGithubEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/bookpi': typeof BookpiRoute
  '/config': typeof ConfigRoute
  '/contracts': typeof ContractsRoute
  '/eoct': typeof EoctRoute
  '/kernel': typeof KernelRoute
  '/korima': typeof KorimaRoute
  '/mdx5': typeof Mdx5Route
  '/rdm': typeof RdmRoute
  '/repos': typeof ReposRoute
  '/federations/$id': typeof FederationsIdRoute
  '/api/github/events': typeof ApiGithubEventsRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/manifest': typeof ApiPublicManifestRouteWithChildren
  '/api/public/query': typeof ApiPublicQueryRoute
  '/api/public/stores': typeof ApiPublicStoresRoute
  '/api/public/systemic': typeof ApiPublicSystemicRoute
  '/api/rdm/manifest': typeof ApiRdmManifestRoute
  '/api/github/events/stream': typeof ApiGithubEventsStreamRoute
  '/api/kernel/artifacts/audit': typeof ApiKernelArtifactsAuditRoute
  '/api/kernel/artifacts/sync': typeof ApiKernelArtifactsSyncRoute
  '/api/public/audit/$traceId': typeof ApiPublicAuditTraceIdRoute
  '/api/public/manifest/compare': typeof ApiPublicManifestCompareRoute
  '/api/public/manifest/history': typeof ApiPublicManifestHistoryRoute
  '/api/rdm/ai/ask': typeof ApiRdmAiAskRoute
  '/api/rdm/auth/register': typeof ApiRdmAuthRegisterRoute
  '/api/rdm/commerce/create': typeof ApiRdmCommerceCreateRoute
  '/api/rdm/economy/reward': typeof ApiRdmEconomyRewardRoute
  '/api/rdm/payments/create': typeof ApiRdmPaymentsCreateRoute
  '/api/rdm/webhooks/stripe': typeof ApiRdmWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/bookpi': typeof BookpiRoute
  '/config': typeof ConfigRoute
  '/contracts': typeof ContractsRoute
  '/eoct': typeof EoctRoute
  '/kernel': typeof KernelRoute
  '/korima': typeof KorimaRoute
  '/mdx5': typeof Mdx5Route
  '/rdm': typeof RdmRoute
  '/repos': typeof ReposRoute
  '/federations/$id': typeof FederationsIdRoute
  '/api/github/events': typeof ApiGithubEventsRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/manifest': typeof ApiPublicManifestRouteWithChildren
  '/api/public/query': typeof ApiPublicQueryRoute
  '/api/public/stores': typeof ApiPublicStoresRoute
  '/api/public/systemic': typeof ApiPublicSystemicRoute
  '/api/rdm/manifest': typeof ApiRdmManifestRoute
  '/api/github/events/stream': typeof ApiGithubEventsStreamRoute
  '/api/kernel/artifacts/audit': typeof ApiKernelArtifactsAuditRoute
  '/api/kernel/artifacts/sync': typeof ApiKernelArtifactsSyncRoute
  '/api/public/audit/$traceId': typeof ApiPublicAuditTraceIdRoute
  '/api/public/manifest/compare': typeof ApiPublicManifestCompareRoute
  '/api/public/manifest/history': typeof ApiPublicManifestHistoryRoute
  '/api/rdm/ai/ask': typeof ApiRdmAiAskRoute
  '/api/rdm/auth/register': typeof ApiRdmAuthRegisterRoute
  '/api/rdm/commerce/create': typeof ApiRdmCommerceCreateRoute
  '/api/rdm/economy/reward': typeof ApiRdmEconomyRewardRoute
  '/api/rdm/payments/create': typeof ApiRdmPaymentsCreateRoute
  '/api/rdm/webhooks/stripe': typeof ApiRdmWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/bookpi': typeof BookpiRoute
  '/config': typeof ConfigRoute
  '/contracts': typeof ContractsRoute
  '/eoct': typeof EoctRoute
  '/kernel': typeof KernelRoute
  '/korima': typeof KorimaRoute
  '/mdx5': typeof Mdx5Route
  '/rdm': typeof RdmRoute
  '/repos': typeof ReposRoute
  '/federations/$id': typeof FederationsIdRoute
  '/api/github/events': typeof ApiGithubEventsRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/manifest': typeof ApiPublicManifestRouteWithChildren
  '/api/public/query': typeof ApiPublicQueryRoute
  '/api/public/stores': typeof ApiPublicStoresRoute
  '/api/public/systemic': typeof ApiPublicSystemicRoute
  '/api/rdm/manifest': typeof ApiRdmManifestRoute
  '/api/github/events/stream': typeof ApiGithubEventsStreamRoute
  '/api/kernel/artifacts/audit': typeof ApiKernelArtifactsAuditRoute
  '/api/kernel/artifacts/sync': typeof ApiKernelArtifactsSyncRoute
  '/api/public/audit/$traceId': typeof ApiPublicAuditTraceIdRoute
  '/api/public/manifest/compare': typeof ApiPublicManifestCompareRoute
  '/api/public/manifest/history': typeof ApiPublicManifestHistoryRoute
  '/api/rdm/ai/ask': typeof ApiRdmAiAskRoute
  '/api/rdm/auth/register': typeof ApiRdmAuthRegisterRoute
  '/api/rdm/commerce/create': typeof ApiRdmCommerceCreateRoute
  '/api/rdm/economy/reward': typeof ApiRdmEconomyRewardRoute
  '/api/rdm/payments/create': typeof ApiRdmPaymentsCreateRoute
  '/api/rdm/webhooks/stripe': typeof ApiRdmWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/bookpi'
    | '/config'
    | '/contracts'
    | '/eoct'
    | '/kernel'
    | '/korima'
    | '/mdx5'
    | '/rdm'
    | '/repos'
    | '/federations/$id'
    | '/api/github/events'
    | '/api/github/webhook'
    | '/api/public/health'
    | '/api/public/ingest'
    | '/api/public/manifest'
    | '/api/public/query'
    | '/api/public/stores'
    | '/api/public/systemic'
    | '/api/rdm/manifest'
    | '/api/github/events/stream'
    | '/api/kernel/artifacts/audit'
    | '/api/kernel/artifacts/sync'
    | '/api/public/audit/$traceId'
    | '/api/public/manifest/compare'
    | '/api/public/manifest/history'
    | '/api/rdm/ai/ask'
    | '/api/rdm/auth/register'
    | '/api/rdm/commerce/create'
    | '/api/rdm/economy/reward'
    | '/api/rdm/payments/create'
    | '/api/rdm/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/bookpi'
    | '/config'
    | '/contracts'
    | '/eoct'
    | '/kernel'
    | '/korima'
    | '/mdx5'
    | '/rdm'
    | '/repos'
    | '/federations/$id'
    | '/api/github/events'
    | '/api/github/webhook'
    | '/api/public/health'
    | '/api/public/ingest'
    | '/api/public/manifest'
    | '/api/public/query'
    | '/api/public/stores'
    | '/api/public/systemic'
    | '/api/rdm/manifest'
    | '/api/github/events/stream'
    | '/api/kernel/artifacts/audit'
    | '/api/kernel/artifacts/sync'
    | '/api/public/audit/$traceId'
    | '/api/public/manifest/compare'
    | '/api/public/manifest/history'
    | '/api/rdm/ai/ask'
    | '/api/rdm/auth/register'
    | '/api/rdm/commerce/create'
    | '/api/rdm/economy/reward'
    | '/api/rdm/payments/create'
    | '/api/rdm/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/bookpi'
    | '/config'
    | '/contracts'
    | '/eoct'
    | '/kernel'
    | '/korima'
    | '/mdx5'
    | '/rdm'
    | '/repos'
    | '/federations/$id'
    | '/api/github/events'
    | '/api/github/webhook'
    | '/api/public/health'
    | '/api/public/ingest'
    | '/api/public/manifest'
    | '/api/public/query'
    | '/api/public/stores'
    | '/api/public/systemic'
    | '/api/rdm/manifest'
    | '/api/github/events/stream'
    | '/api/kernel/artifacts/audit'
    | '/api/kernel/artifacts/sync'
    | '/api/public/audit/$traceId'
    | '/api/public/manifest/compare'
    | '/api/public/manifest/history'
    | '/api/rdm/ai/ask'
    | '/api/rdm/auth/register'
    | '/api/rdm/commerce/create'
    | '/api/rdm/economy/reward'
    | '/api/rdm/payments/create'
    | '/api/rdm/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  BookpiRoute: typeof BookpiRoute
  ConfigRoute: typeof ConfigRoute
  ContractsRoute: typeof ContractsRoute
  EoctRoute: typeof EoctRoute
  KernelRoute: typeof KernelRoute
  KorimaRoute: typeof KorimaRoute
  Mdx5Route: typeof Mdx5Route
  RdmRoute: typeof RdmRoute
  ReposRoute: typeof ReposRoute
  FederationsIdRoute: typeof FederationsIdRoute
  ApiGithubEventsRoute: typeof ApiGithubEventsRouteWithChildren
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicManifestRoute: typeof ApiPublicManifestRouteWithChildren
  ApiPublicQueryRoute: typeof ApiPublicQueryRoute
  ApiPublicStoresRoute: typeof ApiPublicStoresRoute
  ApiPublicSystemicRoute: typeof ApiPublicSystemicRoute
  ApiRdmManifestRoute: typeof ApiRdmManifestRoute
  ApiPublicAuditTraceIdRoute: typeof ApiPublicAuditTraceIdRoute
  ApiRdmAiAskRoute: typeof ApiRdmAiAskRoute
  ApiRdmAuthRegisterRoute: typeof ApiRdmAuthRegisterRoute
  ApiRdmCommerceCreateRoute: typeof ApiRdmCommerceCreateRoute
  ApiRdmEconomyRewardRoute: typeof ApiRdmEconomyRewardRoute
  ApiRdmPaymentsCreateRoute: typeof ApiRdmPaymentsCreateRoute
  ApiRdmWebhooksStripeRoute: typeof ApiRdmWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rdm': {
      id: '/rdm'
      path: '/rdm'
      fullPath: '/rdm'
      preLoaderRoute: typeof RdmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mdx5': {
      id: '/mdx5'
      path: '/mdx5'
      fullPath: '/mdx5'
      preLoaderRoute: typeof Mdx5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/korima': {
      id: '/korima'
      path: '/korima'
      fullPath: '/korima'
      preLoaderRoute: typeof KorimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kernel': {
      id: '/kernel'
      path: '/kernel'
      fullPath: '/kernel'
      preLoaderRoute: typeof KernelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eoct': {
      id: '/eoct'
      path: '/eoct'
      fullPath: '/eoct'
      preLoaderRoute: typeof EoctRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookpi': {
      id: '/bookpi'
      path: '/bookpi'
      fullPath: '/bookpi'
      preLoaderRoute: typeof BookpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/federations/$id': {
      id: '/federations/$id'
      path: '/federations/$id'
      fullPath: '/federations/$id'
      preLoaderRoute: typeof FederationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rdm/manifest': {
      id: '/api/rdm/manifest'
      path: '/api/rdm/manifest'
      fullPath: '/api/rdm/manifest'
      preLoaderRoute: typeof ApiRdmManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/systemic': {
      id: '/api/public/systemic'
      path: '/api/public/systemic'
      fullPath: '/api/public/systemic'
      preLoaderRoute: typeof ApiPublicSystemicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stores': {
      id: '/api/public/stores'
      path: '/api/public/stores'
      fullPath: '/api/public/stores'
      preLoaderRoute: typeof ApiPublicStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/query': {
      id: '/api/public/query'
      path: '/api/public/query'
      fullPath: '/api/public/query'
      preLoaderRoute: typeof ApiPublicQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest': {
      id: '/api/public/manifest'
      path: '/api/public/manifest'
      fullPath: '/api/public/manifest'
      preLoaderRoute: typeof ApiPublicManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/events': {
      id: '/api/github/events'
      path: '/api/github/events'
      fullPath: '/api/github/events'
      preLoaderRoute: typeof ApiGithubEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rdm/webhooks/stripe': {
      id: '/api/rdm/webhooks/stripe'
      path: '/api/rdm/webhooks/stripe'
      fullPath: '/api/rdm/webhooks/stripe'
      preLoaderRoute: typeof ApiRdmWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rdm/payments/create': {
      id: '/api/rdm/payments/create'
      path: '/api/rdm/payments/create'
      fullPath: '/api/rdm/payments/create'
      preLoaderRoute: typeof ApiRdmPaymentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rdm/economy/reward': {
      id: '/api/rdm/economy/reward'
      path: '/api/rdm/economy/reward'
      fullPath: '/api/rdm/economy/reward'
      preLoaderRoute: typeof ApiRdmEconomyRewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rdm/commerce/create': {
      id: '/api/rdm/commerce/create'
      path: '/api/rdm/commerce/create'
      fullPath: '/api/rdm/commerce/create'
      preLoaderRoute: typeof ApiRdmCommerceCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rdm/auth/register': {
      id: '/api/rdm/auth/register'
      path: '/api/rdm/auth/register'
      fullPath: '/api/rdm/auth/register'
      preLoaderRoute: typeof ApiRdmAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rdm/ai/ask': {
      id: '/api/rdm/ai/ask'
      path: '/api/rdm/ai/ask'
      fullPath: '/api/rdm/ai/ask'
      preLoaderRoute: typeof ApiRdmAiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest/history': {
      id: '/api/public/manifest/history'
      path: '/history'
      fullPath: '/api/public/manifest/history'
      preLoaderRoute: typeof ApiPublicManifestHistoryRouteImport
      parentRoute: typeof ApiPublicManifestRoute
    }
    '/api/public/manifest/compare': {
      id: '/api/public/manifest/compare'
      path: '/compare'
      fullPath: '/api/public/manifest/compare'
      preLoaderRoute: typeof ApiPublicManifestCompareRouteImport
      parentRoute: typeof ApiPublicManifestRoute
    }
    '/api/public/audit/$traceId': {
      id: '/api/public/audit/$traceId'
      path: '/api/public/audit/$traceId'
      fullPath: '/api/public/audit/$traceId'
      preLoaderRoute: typeof ApiPublicAuditTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kernel/artifacts/sync': {
      id: '/api/kernel/artifacts/sync'
      path: '/api/kernel/artifacts/sync'
      fullPath: '/api/kernel/artifacts/sync'
      preLoaderRoute: typeof ApiKernelArtifactsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kernel/artifacts/audit': {
      id: '/api/kernel/artifacts/audit'
      path: '/api/kernel/artifacts/audit'
      fullPath: '/api/kernel/artifacts/audit'
      preLoaderRoute: typeof ApiKernelArtifactsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/events/stream': {
      id: '/api/github/events/stream'
      path: '/stream'
      fullPath: '/api/github/events/stream'
      preLoaderRoute: typeof ApiGithubEventsStreamRouteImport
      parentRoute: typeof ApiGithubEventsRoute
    }
  }
}

interface ApiGithubEventsRouteChildren {
  ApiGithubEventsStreamRoute: typeof ApiGithubEventsStreamRoute
}

const ApiGithubEventsRouteChildren: ApiGithubEventsRouteChildren = {
  ApiGithubEventsStreamRoute: ApiGithubEventsStreamRoute,
}

const ApiGithubEventsRouteWithChildren = ApiGithubEventsRoute._addFileChildren(
  ApiGithubEventsRouteChildren,
)

interface ApiPublicManifestRouteChildren {
  ApiPublicManifestCompareRoute: typeof ApiPublicManifestCompareRoute
  ApiPublicManifestHistoryRoute: typeof ApiPublicManifestHistoryRoute
}

const ApiPublicManifestRouteChildren: ApiPublicManifestRouteChildren = {
  ApiPublicManifestCompareRoute: ApiPublicManifestCompareRoute,
  ApiPublicManifestHistoryRoute: ApiPublicManifestHistoryRoute,
}

const ApiPublicManifestRouteWithChildren =
  ApiPublicManifestRoute._addFileChildren(ApiPublicManifestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  BookpiRoute: BookpiRoute,
  ConfigRoute: ConfigRoute,
  ContractsRoute: ContractsRoute,
  EoctRoute: EoctRoute,
  KernelRoute: KernelRoute,
  KorimaRoute: KorimaRoute,
  Mdx5Route: Mdx5Route,
  RdmRoute: RdmRoute,
  ReposRoute: ReposRoute,
  FederationsIdRoute: FederationsIdRoute,
  ApiGithubEventsRoute: ApiGithubEventsRouteWithChildren,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicManifestRoute: ApiPublicManifestRouteWithChildren,
  ApiPublicQueryRoute: ApiPublicQueryRoute,
  ApiPublicStoresRoute: ApiPublicStoresRoute,
  ApiPublicSystemicRoute: ApiPublicSystemicRoute,
  ApiRdmManifestRoute: ApiRdmManifestRoute,
  ApiPublicAuditTraceIdRoute: ApiPublicAuditTraceIdRoute,
  ApiRdmAiAskRoute: ApiRdmAiAskRoute,
  ApiRdmAuthRegisterRoute: ApiRdmAuthRegisterRoute,
  ApiRdmCommerceCreateRoute: ApiRdmCommerceCreateRoute,
  ApiRdmEconomyRewardRoute: ApiRdmEconomyRewardRoute,
  ApiRdmPaymentsCreateRoute: ApiRdmPaymentsCreateRoute,
  ApiRdmWebhooksStripeRoute: ApiRdmWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
